services:
    identity_microservice_database:
        image: mcr.microsoft.com/mssql/server:2022-latest
        container_name: identity_microservice_database
        environment:
            SA_PASSWORD: "${DEFAULT_MSSQL_PASSWORD}"
            ACCEPT_EULA: "Y"
        ports:
            - "${IDENTITY_MICROSERVICE_DATABASE_PORT}:${DATABASE_PORT_INTERNAL}"
        restart: always
        volumes:
            - identity_microservice_volume:/var/opt/mssql

    problem_microservice_database:
        image: mcr.microsoft.com/mssql/server:2022-latest
        container_name: problem_microservice_database
        environment:
            SA_PASSWORD: "${DEFAULT_MSSQL_PASSWORD}"
            ACCEPT_EULA: "Y"
        ports:
            - "${PROBLEM_MICROSERVICE_DATABASE_PORT}:${DATABASE_PORT_INTERNAL}"
        restart: always
        volumes:
            - problem_microservice_volume:/var/opt/mssql

    execution_microservice_database:
        image: mongo:latest
        container_name: execution_microservice_database
        ports:
            - "27017:27017"
        restart: always
        environment:
            - MONGO_INITDB_ROOT_USERNAME=mongoadmin
            - MONGO_INITDB_ROOT_PASSWORD=mnbv0987
        volumes:
            - execution_microservice_volume:/data/db

volumes:
    identity_microservice_volume:
    problem_microservice_volume:
    execution_microservice_volume:
